name: Revisão de Dependências

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Verificar Dependências
        uses: actions/dependency-review-action@v4
